class AppStrings {
  static Map<String, Map<String, String>> strings = {
    'en': {
      'greeting': 'Hi',
      'tagline': 'What do you need today?',
      'tap_to_speak': 'Tap to Speak',
      'listening': 'Listening...',
      'you_said': 'You said:',
      'found': 'Found',
      'categories': 'Categories',
      'add': 'Add',
      'my_cart': 'My Cart',
      'total': 'Total Amount:',
      'place_order': 'Place Order',
      'order_placed': 'Order Placed! 🎉',
      'cart_empty': 'Your cart is empty!',
      'use_voice': 'Use voice search to add products',
      'vegetables': 'Vegetables',
      'fruits': 'Fruits',
      'dairy': 'Dairy',
      'grains': 'Grains',
      'meat': 'Meat',
      'beverages': 'Beverages',
      'login': 'Login',
      'signup': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'name': 'Full Name',
      'phone': 'Phone Number',
      'new_user': 'New user? Sign up',
      'have_account': 'Already have an account? Login',
      'shop_smarter': 'Shop smarter with your voice',
      'create_account': 'Create your account',
      'search_hint': 'Search groceries...',
    },
    'te': {
      'greeting': 'హాయ్',
      'tagline': 'మీకు ఏమి కావాలి?',
      'tap_to_speak': 'మాట్లాడండి',
      'listening': 'వింటున్నాను...',
      'you_said': 'మీరు చెప్పింది:',
      'found': 'దొరికింది',
      'categories': 'వర్గాలు',
      'add': 'జోడించు',
      'my_cart': 'నా కార్ట్',
      'total': 'మొత్తం:',
      'place_order': 'ఆర్డర్ చేయండి',
      'order_placed': 'ఆర్డర్ పూర్తైంది! 🎉',
      'cart_empty': 'మీ కార్ట్ ఖాళీగా ఉంది!',
      'use_voice': 'ఉత్పత్తులు జోడించడానికి వాయిస్ వాడండి',
      'vegetables': 'కూరగాయలు',
      'fruits': 'పండ్లు',
      'dairy': 'పాల ఉత్పత్తులు',
      'grains': 'ధాన్యాలు',
      'meat': 'మాంసం',
      'beverages': 'పానీయాలు',
      'login': 'లాగిన్',
      'signup': 'సైన్ అప్',
      'email': 'ఇమెయిల్',
      'password': 'పాస్‌వర్డ్',
      'name': 'పూర్తి పేరు',
      'phone': 'ఫోన్ నంబర్',
      'new_user': 'కొత్త యూజర్? సైన్ అప్',
      'have_account': 'ఖాతా ఉందా? లాగిన్',
      'shop_smarter': 'మీ వాయిస్‌తో షాపింగ్ చేయండి',
      'create_account': 'మీ ఖాతా సృష్టించండి',
      'search_hint': 'కిరాణా వస్తువులు వెతకండి...',
    },
    'hi': {
      'greeting': 'नमस्ते',
      'tagline': 'आज आपको क्या चाहिए?',
      'tap_to_speak': 'बोलिए',
      'listening': 'सुन रहा हूँ...',
      'you_said': 'आपने कहा:',
      'found': 'मिला',
      'categories': 'श्रेणियाँ',
      'add': 'जोड़ें',
      'my_cart': 'मेरी कार्ट',
      'total': 'कुल राशि:',
      'place_order': 'ऑर्डर करें',
      'order_placed': 'ऑर्डर हो गया! 🎉',
      'cart_empty': 'आपकी कार्ट खाली है!',
      'use_voice': 'उत्पाद जोड़ने के लिए बोलिए',
      'vegetables': 'सब्जियाँ',
      'fruits': 'फल',
      'dairy': 'डेयरी',
      'grains': 'अनाज',
      'meat': 'मांस',
      'beverages': 'पेय पदार्थ',
      'login': 'लॉगिन',
      'signup': 'साइन अप',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'name': 'पूरा नाम',
      'phone': 'फोन नंबर',
      'new_user': 'नए उपयोगकर्ता? साइन अप',
      'have_account': 'खाता है? लॉगिन',
      'shop_smarter': 'अपनी आवाज़ से खरीदारी करें',
      'create_account': 'अपना खाता बनाएं',
      'search_hint': 'किराना खोजें...',
    },
  };

  static String get(String key, String language) {
    return strings[language]?[key] ?? strings['en']![key] ?? key;
  }
}